import type {Metadata} from "next";
import {Merriweather, JetBrains_Mono, Source_Serif_4} from "next/font/google";
import "./globals.css";
import {Footer} from "@/components/footer";
import {Navbar} from "@/components/navbar";

const merriweather = Merriweather({
    subsets: ["latin"],
    weight: ["300", "400", "700", "900"],
    variable: "--font-sans",
});

const sourceSerif = Source_Serif_4({
    subsets: ["latin"],
    variable: "--font-serif",
});

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    variable: "--font-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${merriweather.variable} ${sourceSerif.variable} ${jetbrainsMono.variable} antialiased`}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
